package hr_system_assignment_mtec22_001;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author schirambira
 */
public class frmEmployees extends javax.swing.JFrame {

    DataManager mgr = new DataManager();
    /**
     * Creates new form frmEmployees
     */
    public frmEmployees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtDateHired = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtHoursWorked = new javax.swing.JTextField();
        txtPayRate = new javax.swing.JTextField();
        txtLeaveDays = new javax.swing.JTextField();
        txtCarAllowance = new javax.swing.JTextField();
        txtMonthlyGratuity = new javax.swing.JTextField();
        txtTaxRate = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTotalAllowances = new javax.swing.JTextField();
        txtTotalDeductions = new javax.swing.JTextField();
        txtGrossPay = new javax.swing.JTextField();
        txtNetPay = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cboGender = new javax.swing.JComboBox<>();
        cboPosition = new javax.swing.JComboBox<>();
        cboCity = new javax.swing.JComboBox<>();
        cboDepartment = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Employee ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Date Hired");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Firstname");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Lastname");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Date of Birth");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("City");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Position");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Department");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Hours Worked");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Pay Rate");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Leave Days");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Car Allowance");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Monthly Gratuilty");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Tax Rate");

        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtDateHired.setForeground(new java.awt.Color(0, 0, 102));
        txtDateHired.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtFirstname.setForeground(new java.awt.Color(0, 0, 102));
        txtFirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtLastname.setForeground(new java.awt.Color(0, 0, 102));
        txtLastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtDOB.setForeground(new java.awt.Color(0, 0, 102));
        txtDOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtAddress.setForeground(new java.awt.Color(0, 0, 102));
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtHoursWorked.setBackground(new java.awt.Color(204, 255, 255));
        txtHoursWorked.setForeground(new java.awt.Color(0, 0, 102));
        txtHoursWorked.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtPayRate.setBackground(new java.awt.Color(204, 255, 204));
        txtPayRate.setForeground(new java.awt.Color(0, 0, 102));
        txtPayRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtLeaveDays.setBackground(new java.awt.Color(204, 255, 255));
        txtLeaveDays.setForeground(new java.awt.Color(0, 0, 102));
        txtLeaveDays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtCarAllowance.setEditable(false);
        txtCarAllowance.setBackground(new java.awt.Color(255, 255, 153));
        txtCarAllowance.setForeground(new java.awt.Color(0, 0, 102));
        txtCarAllowance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtMonthlyGratuity.setBackground(new java.awt.Color(204, 255, 255));
        txtMonthlyGratuity.setForeground(new java.awt.Color(0, 0, 102));
        txtMonthlyGratuity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtTaxRate.setBackground(new java.awt.Color(204, 255, 204));
        txtTaxRate.setForeground(new java.awt.Color(0, 0, 102));
        txtTaxRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 0, 153));
        btnCalculate.setText("Calculate Pay");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Total Allowances");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("GROSS PAY");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("Total Deductions");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setText("NET PAY");

        txtTotalAllowances.setEditable(false);
        txtTotalAllowances.setBackground(new java.awt.Color(255, 255, 153));
        txtTotalAllowances.setForeground(new java.awt.Color(0, 0, 102));
        txtTotalAllowances.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtTotalDeductions.setEditable(false);
        txtTotalDeductions.setBackground(new java.awt.Color(255, 255, 153));
        txtTotalDeductions.setForeground(new java.awt.Color(0, 0, 102));
        txtTotalDeductions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtGrossPay.setEditable(false);
        txtGrossPay.setBackground(new java.awt.Color(255, 255, 153));
        txtGrossPay.setForeground(new java.awt.Color(0, 0, 102));
        txtGrossPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtNetPay.setEditable(false);
        txtNetPay.setBackground(new java.awt.Color(255, 255, 153));
        txtNetPay.setForeground(new java.awt.Color(0, 0, 102));
        txtNetPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 153));
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 0, 153));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 0, 153));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cboGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboGender.setForeground(new java.awt.Color(0, 0, 102));
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Female", "Male" }));
        cboGender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        cboPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboPosition.setForeground(new java.awt.Color(0, 0, 102));
        cboPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "CEO", "HR Officer", "Accounts Officer", "Finance Manager", "Support Staff", "Temp Staff" }));
        cboPosition.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        cboPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPositionActionPerformed(evt);
            }
        });

        cboCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboCity.setForeground(new java.awt.Color(0, 0, 102));
        cboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Gaborone", "Francistown", "Maun", "Ghanzi", "Lobatse", "Mahalapye", "Palapye" }));
        cboCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        cboDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboDepartment.setForeground(new java.awt.Color(0, 0, 102));
        cboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Administration", "Marketing", "Information Technology", "Human Resources" }));
        cboDepartment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFirstname)
                                    .addComponent(txtAddress)
                                    .addComponent(txtMonthlyGratuity)
                                    .addComponent(txtEmployeeID)
                                    .addComponent(txtHoursWorked)
                                    .addComponent(txtLeaveDays)
                                    .addComponent(txtTotalAllowances, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtTotalDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(cboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCarAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cboCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)))
                            .addComponent(txtGrossPay, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNetPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(cboPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtLeaveDays, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtMonthlyGratuity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txtTotalAllowances, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrossPay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNetPay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            //clear first
            ClearControls();            

            //initialise
            mgr.InitialiseForm(this, "Welcome To HR-System - ADD EMPLOYEE DETAILS");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        try{
            ClearControls();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
           //validadatate
            String msg = ValidateFormData(true);
            if(msg.trim().length()>0){
                JOptionPane.showMessageDialog(this, msg, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //save details
            String[] data = {   txtEmployeeID.getText(),
                                txtFirstname.getText(),
                                txtLastname.getText(),
                                cboGender.getSelectedItem().toString(),
                                txtDOB.getText(),
                                txtAddress.getText(),
                                cboCity.getSelectedItem().toString(),
                                cboPosition.getSelectedItem().toString(),
                                cboDepartment.getSelectedItem().toString(),
                                txtHoursWorked.getText(),
                                txtPayRate.getText(),
                                txtLeaveDays.getText(),
                                txtCarAllowance.getText(),
                                txtMonthlyGratuity.getText(),
                                txtTaxRate.getText(),
                                txtTotalAllowances.getText(),
                                txtTotalDeductions.getText(),
                                txtGrossPay.getText(),
                                txtNetPay.getText(),
                                txtDateHired.getText()
                            };
            int rows = mgr.WriteFileData("employees.txt", data);
            
            //confirm 
            if(rows > 0){
                JOptionPane.showMessageDialog(this, "Employee pay details saved successfully !!", mgr.GetSystemTitle(), JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Employee pay details saving failed !!", mgr.GetSystemTitle(), JOptionPane.WARNING_MESSAGE);
            }
            //
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try{
           //validadatate
            String msg = ValidateFormData(false);
            if(msg.trim().length()>0){
                JOptionPane.showMessageDialog(this, msg, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //total amount  : hours  rate
            double hoursworked = Double.parseDouble(txtHoursWorked.getText());
            double payrate = Double.parseDouble(txtPayRate.getText());
            double payamount = hoursworked * payrate;
            
            //calculate pay
            double carallowancerate = Double.parseDouble(txtCarAllowance.getText());
            double carallowance = carallowancerate / 100 * payamount;
            
            //gross pay
            double grosspay = payamount + carallowance;
            
            //deductions
            double taxrate = Integer.parseInt(txtTaxRate.getText());
            double taxamount = taxrate/100 * payamount;
            
            //net pay
            double netpay = grosspay - taxamount;
            
            //set values | String.valueOf(value); //change to string
            txtTotalAllowances.setText( RoundOffTo2DecPlaces(carallowance));
            txtTotalDeductions.setText(RoundOffTo2DecPlaces(taxamount));
            txtGrossPay.setText(RoundOffTo2DecPlaces(grosspay));
            txtNetPay.setText(RoundOffTo2DecPlaces(netpay));
            
            //
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cboPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPositionActionPerformed
        // TODO add your handling code here:
        try{
            double carallowancerate = 0;
            if(cboPosition.getSelectedItem().toString().equalsIgnoreCase("HR Officer") || cboPosition.getSelectedItem().toString().equalsIgnoreCase("Accounts Officer")){
                carallowancerate = 15;
            }else if(cboPosition.getSelectedItem().toString().equalsIgnoreCase("CEO")){
                carallowancerate = 30;
            }
            txtCarAllowance.setText(String.valueOf(carallowancerate));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cboPositionActionPerformed

    public String RoundOffTo2DecPlaces(double val) throws Exception {
        return String.format("%.2f", val);
    }
    
    private void SetDefaultValues() throws Exception{
        txtHoursWorked.setText("160"); //default 160 hours | 8 x 5 x 4
        txtPayRate.setText("150");     //default overridable when necessary
        txtTaxRate.setText("14");
        txtLeaveDays.setText("3");
        txtCarAllowance.setText("0");
        txtMonthlyGratuity.setText("25");
    }
        
    private void ClearControls() throws Exception{
        txtEmployeeID.setText("");
        txtDateHired.setText("");
        txtFirstname.setText("");
        txtLastname.setText("");
        cboGender.setSelectedIndex(0);
        txtDOB.setText("");
        txtAddress.setText("");
        cboCity.setSelectedIndex(0);
        cboPosition.setSelectedIndex(0);
        cboDepartment.setSelectedIndex(0);
        txtHoursWorked.setText("");
        txtPayRate.setText("");
        txtLeaveDays.setText("");
        txtCarAllowance.setText("");
        txtMonthlyGratuity.setText("");
        txtTaxRate.setText("");
        txtTotalAllowances.setText("");
        txtTotalDeductions.setText("");
        txtGrossPay.setText("");
        txtNetPay.setText("");
        SetDefaultValues(); //set defaults overridable values
        txtEmployeeID.grabFocus();
    }
    
    private String ValidateFormData(boolean isSaving) throws Exception{
            String msg = "";
            if(txtEmployeeID.getText().equals("")){               msg = "Please enter the employee id before proceeding !!";   
            }else if(txtDateHired.getText().equals("")){          msg = "Please enter the employee date hired before proceeding !!"; 
            }else if(txtFirstname.getText().equals("")){          msg = "Please enter the employee firstname before proceeding !!"; 
            }else if(txtLastname.getText().equals("")){           msg = "Please enter the employee lastname before proceeding !!"; 
            }else if(cboGender.getSelectedIndex()==0){            msg = "Please select the employee gender before proceeding !!"; 
            }else if(txtDOB.getText().equals("")){                msg = "Please enter the employee DOB before proceeding !!"; 
            }else if(txtAddress.getText().equals("")){            msg = "Please enter the employee address before proceeding !!"; 
            }else if(cboCity.getSelectedIndex()==0){              msg = "Please select the employee city before proceeding !!"; 
            }else if(cboPosition.getSelectedIndex()==0){          msg = "Please select the employee position before proceeding !!"; 
            }else if(cboDepartment.getSelectedIndex()==0){        msg = "Please select the employee department before proceeding !!"; 
            }else if(txtHoursWorked.getText().equals("")){        msg = "Please enter the employee hours worked before proceeding !!"; 
            }else if(txtPayRate.getText().equals("")){            msg = "Please enter the employee pay rate before proceeding !!"; 
            }else if(txtLeaveDays.getText().equals("")){          msg = "Please enter the employee leave days before proceeding !!"; 
            }else if(txtCarAllowance.getText().equals("")){       msg = "Please enter the employee car allowance before proceeding !!"; 
            }else if(txtMonthlyGratuity.getText().equals("")){    msg = "Please enter the employee gratuity before proceeding !!"; 
            }else if(txtTaxRate.getText().equals("")){            msg = "Please enter the employee tax rate before proceeding !!"; 
            }
            if(isSaving==true){ //only validate these when saving
                if(txtTotalAllowances.getText().equals("")){    msg = "Please click the calculate button to calculate pay before proceeding !!"; 
                }else if(txtTotalDeductions.getText().equals("")){    msg = "Please click the calculate button to calculate pay before proceeding !!"; 
                }else if(txtGrossPay.getText().equals("")){           msg = "Please click the calculate button to calculate pay before proceeding !!"; 
                }else if(txtNetPay.getText().equals("")){             msg = "Please click the calculate button to calculate pay before proceeding !!"; 
                }
            }
            
            return msg;
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboCity;
    private javax.swing.JComboBox<String> cboDepartment;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCarAllowance;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDateHired;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtGrossPay;
    private javax.swing.JTextField txtHoursWorked;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtLeaveDays;
    private javax.swing.JTextField txtMonthlyGratuity;
    private javax.swing.JTextField txtNetPay;
    private javax.swing.JTextField txtPayRate;
    private javax.swing.JTextField txtTaxRate;
    private javax.swing.JTextField txtTotalAllowances;
    private javax.swing.JTextField txtTotalDeductions;
    // End of variables declaration//GEN-END:variables
}
