
package hr_system_assignment_mtec22_001;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class frmMain extends javax.swing.JFrame {
    DataManager mgr = new DataManager();
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmployeeForm = new javax.swing.JButton();
        btnEmployeeDetails = new javax.swing.JButton();
        btnSearchEmployees = new javax.swing.JButton();
        btnEmployeeSalaries = new javax.swing.JButton();
        btnExitSystem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnEmployeeForm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEmployeeForm.setForeground(new java.awt.Color(255, 0, 153));
        btnEmployeeForm.setText("New Employee Form");
        btnEmployeeForm.setActionCommand("");
        btnEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeFormActionPerformed(evt);
            }
        });

        btnEmployeeDetails.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEmployeeDetails.setForeground(new java.awt.Color(255, 0, 153));
        btnEmployeeDetails.setText("All Employee Details");
        btnEmployeeDetails.setActionCommand("");
        btnEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeDetailsActionPerformed(evt);
            }
        });

        btnSearchEmployees.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSearchEmployees.setForeground(new java.awt.Color(255, 0, 153));
        btnSearchEmployees.setText("Search Employee Details");
        btnSearchEmployees.setActionCommand("");
        btnSearchEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeesActionPerformed(evt);
            }
        });

        btnEmployeeSalaries.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEmployeeSalaries.setForeground(new java.awt.Color(255, 0, 153));
        btnEmployeeSalaries.setText("Employees And Salaries");
        btnEmployeeSalaries.setActionCommand("");
        btnEmployeeSalaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeSalariesActionPerformed(evt);
            }
        });

        btnExitSystem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExitSystem.setForeground(new java.awt.Color(255, 0, 153));
        btnExitSystem.setText("Exit System");
        btnExitSystem.setActionCommand("");
        btnExitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmployeeForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(btnEmployeeSalaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExitSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnEmployeeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnSearchEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEmployeeSalaries, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnExitSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeFormActionPerformed
        // TODO add your handling code here:
        frmEmployees frm = new frmEmployees();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEmployeeFormActionPerformed

    private void btnEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeDetailsActionPerformed
        // TODO add your handling code here:
        frmEmployeeDetails frm = new frmEmployeeDetails();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEmployeeDetailsActionPerformed

    private void btnSearchEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeesActionPerformed
        // TODO add your handling code here:
        frmSearchEmployees frm = new frmSearchEmployees();
        frm.setVisible(true);
    }//GEN-LAST:event_btnSearchEmployeesActionPerformed

    private void btnEmployeeSalariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeSalariesActionPerformed
        // TODO add your handling code here:
        frmEmployeeSalary frm = new frmEmployeeSalary();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEmployeeSalariesActionPerformed

    private void btnExitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSystemActionPerformed
        // TODO add your handling code here:
        
        this.formWindowClosing(null);

    }//GEN-LAST:event_btnExitSystemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            mgr.InitialiseForm(this, "Welcome To HR-System");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int result = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Exit The Application ?", "Exit Application", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            //---do closing functions---//

            //finally close application //
            //--if evt is null, closing is from menuitem, else if not null its from close button: closing handled differently--
            if(evt!=null){this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);} else {System.exit(0);}
        
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeDetails;
    private javax.swing.JButton btnEmployeeForm;
    private javax.swing.JButton btnEmployeeSalaries;
    private javax.swing.JButton btnExitSystem;
    private javax.swing.JButton btnSearchEmployees;
    // End of variables declaration//GEN-END:variables
}
