
package hr_system_assignment_mtec22_001;

import javax.swing.JOptionPane;

public class frmSearchEmployees extends javax.swing.JFrame {
    DataManager mgr = new DataManager();
    
    /**
     * Creates new form frmMain
     */
    public frmSearchEmployees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        cboGender = new javax.swing.JComboBox<>();
        cboPosition = new javax.swing.JComboBox<>();
        cboCity = new javax.swing.JComboBox<>();
        cboDepartment = new javax.swing.JComboBox<>();
        txtEmployeeID = new javax.swing.JTextField();
        txtDateHired = new javax.swing.JTextField();
        chkEmployeeID = new java.awt.Checkbox();
        chkFirstname = new java.awt.Checkbox();
        chkGender = new java.awt.Checkbox();
        chkPosition = new java.awt.Checkbox();
        chkDateHired = new java.awt.Checkbox();
        chkLastname = new java.awt.Checkbox();
        chkCity = new java.awt.Checkbox();
        chkDepartment = new java.awt.Checkbox();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtEmployeeCount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        btnClose.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 153));
        btnClose.setText("Close");
        btnClose.setActionCommand("");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        txtFirstname.setForeground(new java.awt.Color(0, 0, 102));
        txtFirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtLastname.setForeground(new java.awt.Color(0, 0, 102));
        txtLastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        cboGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboGender.setForeground(new java.awt.Color(0, 0, 102));
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Female", "Male" }));
        cboGender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        cboPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboPosition.setForeground(new java.awt.Color(0, 0, 102));
        cboPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "CEO", "HR Officer", "Accounts Officer", "Marketing Officer", "Finance Manager", "Support Staff", "Temp Staff" }));
        cboPosition.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        cboCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboCity.setForeground(new java.awt.Color(0, 0, 102));
        cboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Gaborone", "Francistown", "Maun", "Ghanzi", "Lobatse", "Mahalapye", "Palapye" }));
        cboCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        cboDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboDepartment.setForeground(new java.awt.Color(0, 0, 102));
        cboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Administration", "Marketing", "Information Technology", "Human Resources" }));
        cboDepartment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 102));
        txtEmployeeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtDateHired.setForeground(new java.awt.Color(0, 0, 102));
        txtDateHired.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        chkEmployeeID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkEmployeeID.setForeground(new java.awt.Color(102, 102, 255));
        chkEmployeeID.setLabel("Employee ID");

        chkFirstname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkFirstname.setForeground(new java.awt.Color(102, 102, 255));
        chkFirstname.setLabel("Firstname");

        chkGender.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkGender.setForeground(new java.awt.Color(102, 102, 255));
        chkGender.setLabel("Gender");

        chkPosition.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkPosition.setForeground(new java.awt.Color(102, 102, 255));
        chkPosition.setLabel("Position");

        chkDateHired.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkDateHired.setForeground(new java.awt.Color(102, 102, 255));
        chkDateHired.setLabel("Date Hired");

        chkLastname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkLastname.setForeground(new java.awt.Color(102, 102, 255));
        chkLastname.setLabel("Lastname");

        chkCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkCity.setForeground(new java.awt.Color(102, 102, 255));
        chkCity.setLabel("City");

        chkDepartment.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkDepartment.setForeground(new java.awt.Color(102, 102, 255));
        chkDepartment.setLabel("Department");

        btnSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 0, 153));
        btnSearch.setText("Search");
        btnSearch.setActionCommand("");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 0, 153));
        btnClear.setText("Clear");
        btnClear.setActionCommand("");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 153));
        jLabel18.setText("TOTAL EMPLOYEES : ");

        txtEmployeeCount.setEditable(false);
        txtEmployeeCount.setBackground(new java.awt.Color(153, 255, 255));
        txtEmployeeCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmployeeCount.setForeground(new java.awt.Color(255, 0, 102));
        txtEmployeeCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmployeeCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPosition, 0, 246, Short.MAX_VALUE)
                            .addComponent(txtFirstname))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDateHired)
                            .addComponent(txtLastname)
                            .addComponent(cboCity, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDepartment, javax.swing.GroupLayout.Alignment.TRAILING, 0, 269, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmployeeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkDateHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(chkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEmployeeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            //get criteria chosen 
            int ColumnIndex = 0;
            String ColumnValue="";
            
            //
            if(chkEmployeeID.getState()){
                ColumnIndex = 0;
                ColumnValue = txtEmployeeID.getText().trim();
            }
            //
            if(chkFirstname.getState()){
                ColumnIndex = 1;
                ColumnValue = txtFirstname.getText().trim();
            }
            //
            if(chkLastname.getState()){
                ColumnIndex = 2;
                ColumnValue = txtLastname.getText().trim();
            } 
            //
            if(chkGender.getState()){
                ColumnIndex = 3;
                ColumnValue = cboGender.getSelectedItem().toString();
            }
            //
            if(chkCity.getState()){
                ColumnIndex = 6;
                ColumnValue = cboCity.getSelectedItem().toString();
            }
            //
            if(chkPosition.getState()){
                ColumnIndex = 7;
                ColumnValue = cboPosition.getSelectedItem().toString();
            }
            //
            if(chkDepartment.getState()){
                ColumnIndex = 8;
                ColumnValue = cboDepartment.getSelectedItem().toString();
            }
            //
            if(chkDateHired.getState()){
                ColumnIndex = 19;
                ColumnValue = txtDateHired.getText();
            }
            
            //if not selected raise error message
            if(ColumnValue.equals("")){
                JOptionPane.showMessageDialog(this, "Please select the criteria to search with and enter / select a value before proceeding !!", mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //filter | file, column 0 based position, column value
            String[][] arrdata = mgr.SearchFileData("employees.txt", ColumnIndex, ColumnValue);
            int totalcount = arrdata.length;
            
            //check if found
            if(totalcount==0){
                JOptionPane.showMessageDialog(this, "Your search did not yield any results, please refine your search criteria and try again !!", mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //table
            String[] cols=mgr.GetColumns("Employees");
            mgr.LoadTable(table, arrdata, cols);
            
            //total employees
            txtEmployeeCount.setText(String.valueOf(totalcount));
              
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        try{
            ClearControls();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            //initialise
            mgr.InitialiseForm(this, "Welcome To HR-System - SEARCH EMPLOYEE");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex, mgr.GetSystemTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void ClearControls() throws Exception{
        txtEmployeeID.setText("");
        txtDateHired.setText("");
        txtFirstname.setText("");
        txtLastname.setText("");
        cboGender.setSelectedIndex(0);
        cboCity.setSelectedIndex(0);
        cboPosition.setSelectedIndex(0);
        cboDepartment.setSelectedIndex(0);
        txtEmployeeID.grabFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSearchEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSearchEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSearchEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSearchEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSearchEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboCity;
    private javax.swing.JComboBox<String> cboDepartment;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboPosition;
    private java.awt.Checkbox chkCity;
    private java.awt.Checkbox chkDateHired;
    private java.awt.Checkbox chkDepartment;
    private java.awt.Checkbox chkEmployeeID;
    private java.awt.Checkbox chkFirstname;
    private java.awt.Checkbox chkGender;
    private java.awt.Checkbox chkLastname;
    private java.awt.Checkbox chkPosition;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDateHired;
    private javax.swing.JTextField txtEmployeeCount;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables
}
